### ISSUE TITLE
Maybe add a bit of documentation from your Bash-on-Windows issue

### ISSUE THREAD

**Issue by HenkPoley** [tycho/clockperf#1]
e.g. copy this into a readme: https://github.com/Microsoft/BashOnWindows/issues/77

"To explain the columns .."

**Comment by Karaulov** [comment]
@tycho please decrease ban time to 1 month, or 1 year in this repository https://github.com/ValveSoftware/halflife/issues/2116#issuecomment-477159591 :D 
Thanks)))
