### ISSUE TITLE
Executable hits abort() on line 277 of clockperf.c on macOS High Sierra

### ISSUE THREAD

**Issue by HenkPoley** [tycho/clockperf#3]
Trying to debug this.

The state of `struct clockspec cs` is that it tries to execute the case `CPERF_GETTIME` (= 1) in `clock_read()`, but that case is not built into the executable on macOS (no `gettime()`?). The switch then falls through to the default case, and hits the `abort()`.

line 277: https://github.com/tycho/clockperf/blob/master/clockperf.c#L277

Git version `efaf756` runs just fine on High Sierra. This was built with an older version of macOS though.

**Comment by HenkPoley** [comment]
I wonder if this is a bug in `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platformDeveloper/SDKs/MacOSX.sdk/usr/include/unistd.h`. It defines `_POSIX_TIMERS = -1`.

Since `man clock_gettime` does give results (implemented since macOS 10.12), I tried to move the `#define HAVE_CLOCK_GETTIME` out of the `_POSIX_TIMERS > 0` check. This seems to work.

```
$ ./clockperf
clockperf v1.0.0-4-ge57fd53

Invariant TSC: No

tsc              resolution = 2389MHz
mach_time        resolution = 1000MHz
realtime         resolution = 1000KHz
monotonic        resolution = 1000KHz
monotonic_raw    resolution = 1000MHz
process          resolution = 1000KHz
thread           resolution = 1000MHz
clock            resolution = 1000KHz
time             resolution = 1Hz

Name          Cost(ns)      +/-    Resol  Mono  Fail  Warp  Stal  Regr
tsc              78.17   51.21%     ----    No     0     0     0     0
                 78.17   51.22%
gettimeofday     75.73    5.22%  1000KHz    No     0     0   999     0
mach_time        61.08   22.79%     ----    No     0     0     0     0
                 61.08   22.79%
realtime         83.09    6.44%  1000KHz    No     0     0   999     0
monotonic       109.05    5.39%  1000KHz    No     0     0   999     0
monotonic_raw   107.30   13.67%     ----    No     0     0     0     0
                107.30   13.67%
process         670.96    2.51%  1000KHz    No     0     0   338     0
thread          386.01    5.52%     ----   Yes     0     0     0     0
clock           747.85    6.82%  1000KHz    No     0     0   331     0
ftime            96.20    7.25%   1000Hz    No   982     0    17     0
time            340.63    2.13%      1Hz    No   999     0     0     0
                333.48  142.09%
```

Otherwise it could be possible to use an `#ifdef HAVE_MACH_TIME` in `get_cycles_per_usec()` to set `cs.major = CPERF_MACH_TIME`.

**Comment by tycho** [comment]
Interesting! Thanks for the report, I've pushed a couple changes to fix this.

I should probably introduce a better way to fail out than just calling abort() too, since that makes it surprisingly obnoxious to debug.

**Comment by tycho** [comment]
Also, I love how `CLOCK_MONOTONIC` isn't even monotonically increasing on Mac OS. Doh!

```
Name          Cost(ns)      +/-    Resol  Mono  Fail  Warp  Stal  Regr
monotonic        71.43    0.18%  1000KHz    No     0     0   999     0
```

**Comment by HenkPoley** [comment]
That’s possibly why they don’t define _POSIX_TIMERS as functional. On 10.12 apparently it was defined, but then there was the problem that if you built for older macOS versions, a lot of software would get confused what to do.

**Comment by tycho** [comment]
I'm going to be adding some changes that do a bit of run-time checking to discover which clocks are working properly and can be used for REF_CLOCK, since it's possible that e.g. CLOCK_MONOTONIC is defined, but either not present or wouldn't make for a good reference clock (i.e. isn't actually monotonic).
